# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/lan/Documents/workspace/lightd

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/lan/Documents/workspace/lightd

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Applications/CMake.app/Contents/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Applications/CMake.app/Contents/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/lan/Documents/workspace/lightd/CMakeFiles /Users/lan/Documents/workspace/lightd/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/lan/Documents/workspace/lightd/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lightd

# Build rule for target.
lightd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lightd
.PHONY : lightd

# fast build rule for target.
lightd/fast:
	$(MAKE) -f CMakeFiles/lightd.dir/build.make CMakeFiles/lightd.dir/build
.PHONY : lightd/fast

#=============================================================================
# Target rules for targets named jerry-core

# Build rule for target.
jerry-core: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 jerry-core
.PHONY : jerry-core

# fast build rule for target.
jerry-core/fast:
	$(MAKE) -f jerryscript/jerry-core/CMakeFiles/jerry-core.dir/build.make jerryscript/jerry-core/CMakeFiles/jerry-core.dir/build
.PHONY : jerry-core/fast

#=============================================================================
# Target rules for targets named jerry-ext

# Build rule for target.
jerry-ext: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 jerry-ext
.PHONY : jerry-ext

# fast build rule for target.
jerry-ext/fast:
	$(MAKE) -f jerryscript/jerry-ext/CMakeFiles/jerry-ext.dir/build.make jerryscript/jerry-ext/CMakeFiles/jerry-ext.dir/build
.PHONY : jerry-ext/fast

#=============================================================================
# Target rules for targets named jerry-port-default-minimal

# Build rule for target.
jerry-port-default-minimal: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 jerry-port-default-minimal
.PHONY : jerry-port-default-minimal

# fast build rule for target.
jerry-port-default-minimal/fast:
	$(MAKE) -f jerryscript/jerry-port/default/CMakeFiles/jerry-port-default-minimal.dir/build.make jerryscript/jerry-port/default/CMakeFiles/jerry-port-default-minimal.dir/build
.PHONY : jerry-port-default-minimal/fast

#=============================================================================
# Target rules for targets named jerry-port-default

# Build rule for target.
jerry-port-default: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 jerry-port-default
.PHONY : jerry-port-default

# fast build rule for target.
jerry-port-default/fast:
	$(MAKE) -f jerryscript/jerry-port/default/CMakeFiles/jerry-port-default.dir/build.make jerryscript/jerry-port/default/CMakeFiles/jerry-port-default.dir/build
.PHONY : jerry-port-default/fast

#=============================================================================
# Target rules for targets named jerry

# Build rule for target.
jerry: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 jerry
.PHONY : jerry

# fast build rule for target.
jerry/fast:
	$(MAKE) -f jerryscript/jerry-main/CMakeFiles/jerry.dir/build.make jerryscript/jerry-main/CMakeFiles/jerry.dir/build
.PHONY : jerry/fast

#=============================================================================
# Target rules for targets named light

# Build rule for target.
light: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 light
.PHONY : light

# fast build rule for target.
light/fast:
	$(MAKE) -f components/light/CMakeFiles/light.dir/build.make components/light/CMakeFiles/light.dir/build
.PHONY : light/fast

#=============================================================================
# Target rules for targets named module

# Build rule for target.
module: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 module
.PHONY : module

# fast build rule for target.
module/fast:
	$(MAKE) -f components/module/CMakeFiles/module.dir/build.make components/module/CMakeFiles/module.dir/build
.PHONY : module/fast

src/jerry.o: src/jerry.c.o

.PHONY : src/jerry.o

# target to build an object file
src/jerry.c.o:
	$(MAKE) -f CMakeFiles/lightd.dir/build.make CMakeFiles/lightd.dir/src/jerry.c.o
.PHONY : src/jerry.c.o

src/jerry.i: src/jerry.c.i

.PHONY : src/jerry.i

# target to preprocess a source file
src/jerry.c.i:
	$(MAKE) -f CMakeFiles/lightd.dir/build.make CMakeFiles/lightd.dir/src/jerry.c.i
.PHONY : src/jerry.c.i

src/jerry.s: src/jerry.c.s

.PHONY : src/jerry.s

# target to generate assembly for a file
src/jerry.c.s:
	$(MAKE) -f CMakeFiles/lightd.dir/build.make CMakeFiles/lightd.dir/src/jerry.c.s
.PHONY : src/jerry.c.s

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/lightd.dir/build.make CMakeFiles/lightd.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/lightd.dir/build.make CMakeFiles/lightd.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/lightd.dir/build.make CMakeFiles/lightd.dir/src/main.c.s
.PHONY : src/main.c.s

src/worker.o: src/worker.c.o

.PHONY : src/worker.o

# target to build an object file
src/worker.c.o:
	$(MAKE) -f CMakeFiles/lightd.dir/build.make CMakeFiles/lightd.dir/src/worker.c.o
.PHONY : src/worker.c.o

src/worker.i: src/worker.c.i

.PHONY : src/worker.i

# target to preprocess a source file
src/worker.c.i:
	$(MAKE) -f CMakeFiles/lightd.dir/build.make CMakeFiles/lightd.dir/src/worker.c.i
.PHONY : src/worker.c.i

src/worker.s: src/worker.c.s

.PHONY : src/worker.s

# target to generate assembly for a file
src/worker.c.s:
	$(MAKE) -f CMakeFiles/lightd.dir/build.make CMakeFiles/lightd.dir/src/worker.c.s
.PHONY : src/worker.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... lightd"
	@echo "... jerry-core"
	@echo "... jerry-ext"
	@echo "... jerry-port-default-minimal"
	@echo "... jerry-port-default"
	@echo "... jerry"
	@echo "... light"
	@echo "... module"
	@echo "... src/jerry.o"
	@echo "... src/jerry.i"
	@echo "... src/jerry.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/worker.o"
	@echo "... src/worker.i"
	@echo "... src/worker.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

